name: Build Android UE Dumper

on:
  workflow_dispatch: # 网页手动触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Android NDK r29
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r29-linux.zip
          unzip -q android-ndk-r29-linux.zip
          echo "ANDROID_NDK_ROOT=$PWD/android-ndk-r29" >> $GITHUB_ENV
          # 创建软链接，适配Makefile写死的 /ndk-build
          sudo ln -s $PWD/android-ndk-r29/ndk-build /ndk-build

      - name: Compile project
        run: |
          ls -la
          cd ./AndUEDumper
          ls -la
          make clean && make
          ls -la out/

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: "**/out/*"
