name: Build Android UE Dumper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Android NDK r25c
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_ROOT=$PWD/android-ndk-r25c" >> $GITHUB_ENV
          sudo ln -s $PWD/android-ndk-r25c/ndk-build /ndk-build

      - name: Compile project
        run: |
          cd ./AndUEDumper
          make clean && make
          ls -la out/

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: "**/out/*"
